### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lf-araujo** [nglgzz/albert-plugins#1]
Thanks for this code!

Now, where should I install them? Seems like albert's api changed a bit.

**Comment by nglgzz** [comment]
Hey, thank you for checking out the project!

I'm not sure if it works the same on all distros, but on Arch I just clone this repo to:

    ~/.local/share/albert/org.albert.extension.python/modules

Let me know if that works :)

**Comment by lf-araujo** [comment]
Yes, it does. Thanks!
