### ISSUE TITLE
Plugin to search personal repos only

### ISSUE THREAD

**Issue by bhishanpdl** [nglgzz/albert-plugins#2]
Hi nglgzz,

The Albert plugin to search GitHub repo was very useful, is there a way the script `github.py` be changed so that it only search our personal GitHub repos only?

**Comment by nglgzz** [comment]
Hey @bhishanpdl, 

Yes it's an easy change actually. Just add `user:<your_username>` to the search query. So in your case you can replace [this line](https://github.com/nglgzz/albert-plugins/blob/master/github.py#L56) with `"q": "user:bhishanpdl " + query`.

You can find a list of all possible search parameters [on GitHub docs](https://help.github.com/articles/searching-for-repositories/)
